### ISSUE TITLE
create Project Map view

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#110]

**Comment by daniellerad** [comment]
Map should contain pins on countries that have projects. Clicking the pin brings up a scrolling pop-up or light box featuring all the projects in that country for the filter range set on the map. Each project name links to project page.

**Filters (perhaps housed in a call-out menu from a search icon? Filters will be applied using an AND relationship between filters (e.g. if you select a Grantee and an Issue, you'll get projects that satisfy both, as opposed to a combination of projects by that grantee and projects in that issue) and an OR relationship within filters (e.g. if you select one grantee and multiple issues you'll get projects that are by that grantee and reference any of the selected issues).):**
Project year (including all time) - range filter based on post date
Issue
Topic
Region
Country
Grantee Name (rather than a list, use a search box that pops up suggested names as people type)
Student Fellows only
Campus Consortium Partners
Publication

Sharing for each pre-filtered view: "This will be possible given that every filtered map will generate its own URL - but it will be pretty funky-looking machine-generated text strings (especially when multiple filter criteria are selected). You can use URL redirects within Drupal to provide a prettier shortcut URL. Depending on how we're doing with hours once we get into development, we may be able to also implement a URL-shortener-esque permalink solution that would allow users to share their filtered map using a shortened hashed link (similar to a bitly link). It will be important for Pulitzer to optimize Open Graph and Twitter metadata for the map so that information (when populated by FB or Twitter or whatever) is broad enough to make sense for all map social sharing. "

**Comment by xaqrox** [comment]
Start here:
>Map should contain pins on countries that have projects. Clicking the pin brings up a scrolling pop-up or light box featuring all the projects in that country for the filter range set on the map. Each project name links to project page.

**Comment by xaqrox** [comment]
I don't know if this will be useful, but it's lovely http://mbostock.github.io/d3/talk/20111018/azimuthal.html
