### ISSUE TITLE
items missing from create content admin menu

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#294]
Please figure out why Story, Pulitzer Center Update, Education Resource are not appearing under Create Content in admin menu

**Comment by jselt** [comment]
So this was due to these being disabled in the "Navigation" menu - which Admin Menu looks at to build that create content subnav.

In #268 Xaq is scripting some menu items so it's probably best to include this there

@xaqrox Ensure that "Education Resource, "Pulitzer Center Update, and "Story" are enabled in the navigation menu. Parent is "Create content". Also change the menu title of Gateway to Issue. Probably best to disable "Post" as well.
