### ISSUE TITLE
update story related information view

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#36]

**Comment by daniellerad** [comment]
Re-opening this, but it's not a walk-through blocker.

When you click on the Related Information terms in the sidebar of a project or Story/PC Update/Ed Resource, you get to a list page that's pretty ugly if you're looking at a Region or County or Media or Blog term. (Topic is fine since it will have a nicely styled landing page. Campus Consortium member pages seem to have basic pages for each university, so those are fine, too. e.g. http://pccr.radcampaign.com/campus-consortium/kent-state-university)

Is it possible to make the Region/Country/Media/Blog term links point to the pre-filtered Reporting page?

So, instead of Country: Kenya linking to http://pccr.radcampaign.com/country/kenya it would link to http://pccr.radcampaign.com/reporting?keys=&pubdate%5Bmin%5D%5Bdate%5D=&pubdate%5Bmax%5D%5Bdate%5D=&issue=All&tag=All&region=All&country=Kenya&author=All&Publication=&media=All

Here are some more examples of the current list pages for reference. It looks like the Media URLs might be aliases/redirects?:

http://pccr.radcampaign.com/region/africa (e.g. Region)

http://pccr.radcampaign.com/articles (Media: Article)
http://pccr.radcampaign.com/books (Media: Books)
http://pccr.radcampaign.com/e-books (Media: E-books)
http://pccr.radcampaign.com/podcast (Media: Field Notes)
http://pccr.radcampaign.com/audio (Media: Audio)
http://pccr.radcampaign.com/interactive (Media: Interactive)
http://pccr.radcampaign.com/slideshows (Media: Photo)
http://pccr.radcampaign.com/video (Media: Video)

http://pccr.radcampaign.com/blog/news (Blog: General News)
http://pccr.radcampaign.com/blog/education-news (Blog: Education News)
http://pccr.radcampaign.com/blog/awards (Blog: Awards)
http://pccr.radcampaign.com/blog/project-news (Blog: Project News)

**Comment by xaqrox** [comment]
Gonna be handled by [Term Page stuff](https://github.com/radcampaign/pulitzer2016/milestone/7)
