### ISSUE TITLE
Student Fellow content in dashboard and status summary emails

### ISSUE THREAD

**Issue by daniellerad** [radcampaign/pulitzer2016#393]
Untold Stories submitted by student fellows are not showing up in the Dashboard or daily status summary emails.

Our first student fellow to submit since the launch, Yardain Amron, submitted three stories, but none showed up in the dashboard or in the status summary emails. Kem received two alerts for each, however—one that says "new story" and one that says "new student fellow story."

Here are the stories:
India: How a Sanitation Scheme Perpetuated Brick Bondage
Podcast: The Stigmas of Bondage
India: Fighting Brick Bondage With Unity

**Comment by daniellerad** [comment]
http://pulitzercenter.org/admin/dashboard

For the status summary email, they should appear under the “Student Fellows” section.

India: How a Sanitation Scheme Perpetuated Brick Bondage – http://pulitzercenter.org/reporting/india-how-sanitation-scheme-perpetuated-brick-bondage
Podcast: The Stigmas of Bondage – http://pulitzercenter.org/reporting/podcast-stigmas-bondage
India: Fighting Brick Bondage With Unity – http://pulitzercenter.org/reporting/india-fighting-brick-bondage-unity

**Comment by xaqrox** [comment]
Two separate issues:
### Dashboard
This isn't pulling any of the types that Post turned into. Just need to add that.
### Status email
Right now I can see the two item that start with "India". The "Podcast" one is missing. The view pulls in
- **unpublished** nodes
- of type **Story**
- that are **not "hide from status"** (whyyy)
- _AND_
- have an **node author** _OR_ **reference a user via `field_authors`**  "Student Fellow"

The problem is for some reason views is doing an inner join on the `field_authors` table, so that any nodes with no value for that field get excluded. That is the case with "Podcast: The Stigmas of Bondage". To be clear, I don't think any of our work caused this problem, because this behavior does nto match the logic described above which makes it a bug in views IMHO.

So, three options:
1. Lose that filter. If stories that might have a student fellow in referenced in `field_authors` are always also literally authored by a Student Fellow user, it's not necessary.
2. Always make sure the author is referenced in the authors field. This could be a rule for content managers, or we could automate it.
3. Debug views. This one is intimidating.

**Comment by daniellerad** [comment]
@xaqrox For the status summary email, are the view filters you noted only for the Student Fellows section?

**Comment by xaqrox** [comment]
@daniellerad I don't know, each section of the status email is a separate view display, I've only looked at this one this far. Will take a look at the others.

**Comment by daniellerad** [comment]
I just wonder if I need to think through every section if we choose option 1, or if it can be a contained change to only the Student Fellows section.

**Comment by xaqrox** [comment]
the only other section that uses a role filter on the `field_authors` relationship is "Internal"

**Comment by daniellerad** [comment]
If we remove the `field_authors` filter from Student Fellows, does it also remove it from Internal?

**Comment by xaqrox** [comment]
No. But who knows if that is working the way they think it's working.

**Comment by daniellerad** [comment]
Ok. Thanks for the info. Will circle back.

**Comment by daniellerad** [comment]
Xaq will send PC a list of "missed" Student Fellows content.

Xaq will create a rule that, on the first node save it will automatically fill in the People field with the user authoring the node, only if People is empty.

**Comment by daniellerad** [comment]
Green light to deploy with #395 (when that's ready).
