### ISSUE TITLE
create upcoming/ongoing events view

### ISSUE THREAD

**Issue by xaqrox** [radcampaign/pulitzer2016#67]

**Comment by jselt** [comment]
2 questions

1) RSVP and Learn More - they seem to have usually added the text Learn More to the link field (which usually goes to an external link to RSVP) -should I override that and link to the node with Learn More when the link field is empty?

2) Are the "participants names supposed to be linked to their profiles or do we want to cut down on clicking away.

**Comment by daniellerad** [comment]
1. Yes - they just wanted some flexibility in the button label because every event is different (some have RSVP, some don't, whatever). If there is no external link included, then yes - please have that button link to the node.

2. It would be great to link to the participants profiles, if it's not too much hassle.

**Comment by jselt** [comment]
1) K
2) it's just a setting, I would turn it off personally, but I can re-enable

**Comment by daniellerad** [comment]
2. Just realized you were talking about the Events landing (not the individual event) - agreed, please don't link.

**Comment by jselt** [comment]
One more question: should the search include past events?

**Comment by daniellerad** [comment]
I think so. They don't typically have that many upcoming events, so you could probably browse upcoming events just as easily as searching. But someone may be looking for a specific past event.
